<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Focus-QA-29" ignored="1" name="Test5" tests="3" failures="2" timestamp="15 Feb 2019 07:38:15 GMT" time="0.047" errors="0">
  <testcase name="exchRateNames" time="0.016" classname="com.teyseer.com.teyseer.tests.ExchangeRate">
    <failure type="java.io.FileNotFoundException" message="\\DESKTOP-C918GTA\Keywords\ExchRate Names Sheet.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)">
      <![CDATA[java.io.FileNotFoundException: \\DESKTOP-C918GTA\Keywords\ExchRate Names Sheet.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.teyseer.com.teyseer.tests.ExchangeRate.exchRateNames(ExchangeRate.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- exchRateNames -->
  <testcase name="exchRate" time="0.0" classname="com.teyseer.com.teyseer.tests.ExchangeRate"/>
  <testcase name="testResults" time="0.016" classname="com.teyseer.com.teyseer.tests.TestResults">
    <failure type="java.io.FileNotFoundException" message="\\DESKTOP-C918GTA\Keywords\Automation Test Cases\Test Results.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)">
      <![CDATA[java.io.FileNotFoundException: \\DESKTOP-C918GTA\Keywords\Automation Test Cases\Test Results.xlsx (The system cannot contact a domain controller to service the authentication request. Please try again later)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.teyseer.com.teyseer.tests.TestResults.testResults(TestResults.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testResults -->
  <testcase name="@BeforeSuite LaunchApp" time="0.0" classname="com.focus.constants.LaunchApplication">
    <ignored/>
  </testcase> <!-- @BeforeSuite LaunchApp -->
</testsuite> <!-- Test5 -->
